package med.mybatis.model;

import java.util.List;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.EMAIL
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.SPECIALIZATION
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String specialization;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.ID
     *
     * @return the value of PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.ID
     *
     * @param id the value for PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.EMAIL
     *
     * @return the value of PUBLIC.DOCTOR.EMAIL
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.EMAIL
     *
     * @param email the value for PUBLIC.DOCTOR.EMAIL
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.LASTNAME
     *
     * @return the value of PUBLIC.DOCTOR.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.LASTNAME
     *
     * @param lastname the value for PUBLIC.DOCTOR.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @return the value of PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @param name the value for PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.PHONE_NUMBER
     *
     * @return the value of PUBLIC.DOCTOR.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.PHONE_NUMBER
     *
     * @param phoneNumber the value for PUBLIC.DOCTOR.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.SPECIALIZATION
     *
     * @return the value of PUBLIC.DOCTOR.SPECIALIZATION
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getSpecialization() {
        return specialization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.SPECIALIZATION
     *
     * @param specialization the value for PUBLIC.DOCTOR.SPECIALIZATION
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }

    //added by hand:

    private List<Visit> visits;
    public List<Visit> getVisits() {
        return visits;
    }

    public void setVisits(List<Visit> visits) {
        this.visits = visits;
    }
}