package med.mybatis.model;

import java.util.Date;

public class MedicalHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICAL_HISTORY.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICAL_HISTORY.DISEASE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String disease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_DEC
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String treatmentDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_START
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Date treatmentStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICAL_HISTORY.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer patientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICAL_HISTORY.ID
     *
     * @return the value of PUBLIC.MEDICAL_HISTORY.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICAL_HISTORY.ID
     *
     * @param id the value for PUBLIC.MEDICAL_HISTORY.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICAL_HISTORY.DISEASE
     *
     * @return the value of PUBLIC.MEDICAL_HISTORY.DISEASE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICAL_HISTORY.DISEASE
     *
     * @param disease the value for PUBLIC.MEDICAL_HISTORY.DISEASE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setDisease(String disease) {
        this.disease = disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_DEC
     *
     * @return the value of PUBLIC.MEDICAL_HISTORY.TREATMENT_DEC
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getTreatmentDec() {
        return treatmentDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_DEC
     *
     * @param treatmentDec the value for PUBLIC.MEDICAL_HISTORY.TREATMENT_DEC
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setTreatmentDec(String treatmentDec) {
        this.treatmentDec = treatmentDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_START
     *
     * @return the value of PUBLIC.MEDICAL_HISTORY.TREATMENT_START
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Date getTreatmentStart() {
        return treatmentStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICAL_HISTORY.TREATMENT_START
     *
     * @param treatmentStart the value for PUBLIC.MEDICAL_HISTORY.TREATMENT_START
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setTreatmentStart(Date treatmentStart) {
        this.treatmentStart = treatmentStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICAL_HISTORY.PATIENT_ID
     *
     * @return the value of PUBLIC.MEDICAL_HISTORY.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICAL_HISTORY.PATIENT_ID
     *
     * @param patientId the value for PUBLIC.MEDICAL_HISTORY.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
}