package med.mybatis.model;

import java.util.Date;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.BIRTH_DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.ID
     *
     * @return the value of PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.ID
     *
     * @param id the value for PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.BIRTH_DATE
     *
     * @return the value of PUBLIC.PATIENT.BIRTH_DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.BIRTH_DATE
     *
     * @param birthDate the value for PUBLIC.PATIENT.BIRTH_DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.LASTNAME
     *
     * @return the value of PUBLIC.PATIENT.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.LASTNAME
     *
     * @param lastname the value for PUBLIC.PATIENT.LASTNAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.NAME
     *
     * @return the value of PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.NAME
     *
     * @param name the value for PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @return the value of PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @param phoneNumber the value for PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}