package med.mybatis.model;

public class PatientDoctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT_DOCTOR.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT_DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT_DOCTOR.PATIENT_ID
     *
     * @return the value of PUBLIC.PATIENT_DOCTOR.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT_DOCTOR.PATIENT_ID
     *
     * @param patientId the value for PUBLIC.PATIENT_DOCTOR.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT_DOCTOR.DOCTOR_ID
     *
     * @return the value of PUBLIC.PATIENT_DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT_DOCTOR.DOCTOR_ID
     *
     * @param doctorId the value for PUBLIC.PATIENT_DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
}