package med.mybatis.model;

import java.util.Date;

public class Visit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.NOTES
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VISIT.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    private Integer patientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.ID
     *
     * @return the value of PUBLIC.VISIT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.ID
     *
     * @param id the value for PUBLIC.VISIT.ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.DATE
     *
     * @return the value of PUBLIC.VISIT.DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.DATE
     *
     * @param date the value for PUBLIC.VISIT.DATE
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.NAME
     *
     * @return the value of PUBLIC.VISIT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.NAME
     *
     * @param name the value for PUBLIC.VISIT.NAME
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.NOTES
     *
     * @return the value of PUBLIC.VISIT.NOTES
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.NOTES
     *
     * @param notes the value for PUBLIC.VISIT.NOTES
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.DOCTOR_ID
     *
     * @return the value of PUBLIC.VISIT.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.DOCTOR_ID
     *
     * @param doctorId the value for PUBLIC.VISIT.DOCTOR_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VISIT.PATIENT_ID
     *
     * @return the value of PUBLIC.VISIT.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VISIT.PATIENT_ID
     *
     * @param patientId the value for PUBLIC.VISIT.PATIENT_ID
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
}