package med.mybatis.dao;

import java.util.List;
import med.mybatis.model.Doctor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    Doctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int updateByPrimaryKey(Doctor record);

    List<Doctor> findDoctorWithVisits();
}