package med.mybatis.dao;

import java.util.List;
import med.mybatis.model.MedicalHistory;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MedicalHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICAL_HISTORY
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICAL_HISTORY
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int insert(MedicalHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICAL_HISTORY
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    MedicalHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICAL_HISTORY
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    List<MedicalHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICAL_HISTORY
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int updateByPrimaryKey(MedicalHistory record);
}