package med.mybatis.dao;

import java.util.List;
import med.mybatis.model.Patient;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int updateByPrimaryKey(Patient record);
}