package med.mybatis.dao;

import java.util.List;
import med.mybatis.model.PatientDoctor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PatientDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT_DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int insert(PatientDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT_DOCTOR
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    List<PatientDoctor> selectAll();
}