package med.mybatis.dao;

import java.util.List;
import med.mybatis.model.Visit;
import org.mybatis.cdi.Mapper;

@Mapper
public interface VisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VISIT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VISIT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int insert(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VISIT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    Visit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VISIT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    List<Visit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VISIT
     *
     * @mbg.generated Mon Apr 07 12:33:12 EEST 2025
     */
    int updateByPrimaryKey(Visit record);
}